# generated by datamodel-codegen:
#   filename:  ws.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class Flag(StrEnum):
    military = 'military'
    emergency = 'emergency'
    watchlist = 'watchlist'


class TrailItem(RootModel[list[float]]):
    root: list[float]


class Enrichment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registration: str | None = None
    typeCode: str | None = None
    typeName: str | None = None
    operator: str | None = None
    country: str | None = None
    route: str | None = None
    photoUrl: str | None = None


class Vessel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mmsi: int
    name: str | None = None
    lat: confloat(ge=-90.0, le=90.0)
    lon: confloat(ge=-180.0, le=180.0)
    sogKt: float | None = None
    cogDeg: float | None = None
    shipType: int | None = None
    lastSeen: int


class Mode(StrEnum):
    atc = 'atc'
    ais = 'ais'
    satellite = 'satellite'
    idle = 'idle'
    faulted = 'faulted'
    offline = 'offline'


class Reason(StrEnum):
    schedule = 'schedule'
    preempt = 'preempt'
    manual = 'manual'
    fault = 'fault'
    lwt = 'lwt'


class NextPass(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    satellite: str
    aos: int
    los: int
    maxEl: confloat(ge=0.0, le=90.0)


class Status(StrEnum):
    scheduled = 'scheduled'
    captured = 'captured'
    decoded = 'decoded'
    failed = 'failed'


class PassSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    satellite: str
    aos: int
    los: int
    maxElevation: float
    status: Status
    imageUrls: list[str]


class NodeHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: bool
    cpuPct: confloat(ge=0.0)
    memMb: confloat(ge=0.0)
    tempC: float
    throttled: bool
    diskFreePct: confloat(ge=0.0, le=100.0)


class AdsbHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: bool
    msgRate: confloat(ge=0.0)
    aircraftCount: conint(ge=0)
    maxRangeKm: confloat(ge=0.0)


class SystemHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodeA: NodeHealth
    nodeB: NodeHealth | None = Field(..., description='null = offline (MQTT LWT fired)')
    adsb: AdsbHealth
    dbOk: bool


class VesselDeltaMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['vessel_delta']
    ts: int
    updated: list[Vessel]
    removed: list[int]


class AtcActivityMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['atc_activity']
    ts: int
    channelMhz: float
    active: bool


class Severity(StrEnum):
    critical = 'critical'
    notable = 'notable'


class InterestingMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['interesting']
    ts: int
    icao: constr(pattern=r'^[0-9a-f]{6}$')
    severity: Severity
    rule: str
    callsign: str | None


class PassUpdateMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['pass_update']
    ts: int
    pass_: PassSummary = Field(..., alias='pass')


class SystemHealthMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['system_health']
    ts: int
    health: SystemHealth


class Topic(StrEnum):
    aircraft = 'aircraft'
    vessels = 'vessels'
    radio2 = 'radio2'
    system = 'system'


class SubscribeMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['subscribe']
    topics: list[Topic]


class PingMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ping']
    ts: int


class ClientMessage(RootModel[SubscribeMessage | PingMessage]):
    root: SubscribeMessage | PingMessage


class Aircraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    icao: constr(pattern=r'^[0-9a-f]{6}$')
    callsign: str | None = None
    lat: confloat(ge=-90.0, le=90.0) | None = None
    lon: confloat(ge=-180.0, le=180.0) | None = None
    altFt: int | None = None
    gsKt: float | None = None
    vrFpm: float | None = None
    track: confloat(ge=0.0, lt=360.0) | None = None
    squawk: constr(pattern=r'^[0-7]{4}$') | None = None
    distanceKm: confloat(ge=0.0) | None = None
    bearingDeg: confloat(ge=0.0, lt=360.0) | None = None
    priority: conint(ge=0)
    flags: list[Flag]
    enrich: Enrichment | None = None
    trail: list[TrailItem] = Field(..., max_length=100)
    lastSeen: int = Field(..., description='unix seconds')
    rssi: float | None = None


class Radio2Status(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Mode
    since: int
    reason: Reason
    nextPass: NextPass | None
    audioUrl: str | None
    tleAgeDays: confloat(ge=0.0)


class SnapshotMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['snapshot']
    ts: int
    aircraft: list[Aircraft]
    vessels: list[Vessel]
    radio2: Radio2Status
    latestPass: PassSummary | None
    health: SystemHealth


class AircraftDeltaMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['aircraft_delta']
    ts: int
    updated: list[Aircraft]
    removed: list[constr(pattern=r'^[0-9a-f]{6}$')]


class Radio2StatusMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['radio2_status']
    ts: int
    status: Radio2Status


class ServerMessage(
    RootModel[
        SnapshotMessage
        | AircraftDeltaMessage
        | VesselDeltaMessage
        | Radio2StatusMessage
        | AtcActivityMessage
        | InterestingMessage
        | PassUpdateMessage
        | SystemHealthMessage
    ]
):
    root: (
        SnapshotMessage
        | AircraftDeltaMessage
        | VesselDeltaMessage
        | Radio2StatusMessage
        | AtcActivityMessage
        | InterestingMessage
        | PassUpdateMessage
        | SystemHealthMessage
    )


class WsMessages(RootModel[ServerMessage | ClientMessage]):
    root: ServerMessage | ClientMessage = Field(
        ...,
        description='WebSocket protocol between gateway and browser clients. Source of truth: 03_PROJECT_SPEC §3.1.',
        title='WsMessages',
    )
