# generated by datamodel-codegen:
#   filename:  mqtt.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class Mode(StrEnum):
    atc = 'atc'
    ais = 'ais'
    satellite = 'satellite'
    idle = 'idle'
    faulted = 'faulted'


class Reason(StrEnum):
    schedule = 'schedule'
    preempt = 'preempt'
    manual = 'manual'
    fault = 'fault'
    boot = 'boot'


class Radio2Mode(BaseModel):
    """
    topic: radio2/mode (retained, QoS1)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    mode: Mode
    since: int
    reason: Reason
    pid: int | None = None


class Radio2PassNext(BaseModel):
    """
    topic: radio2/pass/next (retained, QoS1); payload may be null-equivalent via satellite:null when no pass scheduled
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    satellite: str | None
    aos: int | None
    los: int | None
    maxEl: float | None


class Radio2Health(BaseModel):
    """
    topic: radio2/health (retained, QoS1, LWT sets ok:false reason:offline)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    ok: bool
    decoder: str | None = None
    uptimeS: int | None = None
    reason: str | None = None
    tleAgeDays: float | None = None


class Mode1(StrEnum):
    atc = 'atc'
    ais = 'ais'
    satellite = 'satellite'
    idle = 'idle'
    auto = 'auto'


class Radio2Command(BaseModel):
    """
    topic: radio2/cmd (QoS1, not retained) — gateway-issued manual override
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    mode: Mode1
    durationS: conint(ge=1) | None = None
    force: bool | None = False


class AtcActivity(BaseModel):
    """
    topic: atc/activity (QoS0)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    channelMhz: float
    active: bool


class AisVessel(BaseModel):
    """
    topic: ais/vessel (QoS0)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    mmsi: int
    lat: confloat(ge=-90.0, le=90.0)
    lon: confloat(ge=-180.0, le=180.0)
    sogKt: float | None = None
    cogDeg: float | None = None
    name: str | None = None
    shipType: int | None = None


class Status(StrEnum):
    scheduled = 'scheduled'
    capturing = 'capturing'
    captured = 'captured'
    decoding = 'decoding'
    decoded = 'decoded'
    failed = 'failed'


class SatellitePassEvent(BaseModel):
    """
    topic: satellite/pass/event (QoS1)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    passId: int
    satellite: str
    status: Status
    images: list[str] | None = None
    note: str | None = None


class SysHealth(BaseModel):
    """
    topic: sys/{node}/health (retained, QoS1, LWT sets ok:false)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    ok: bool
    cpuPct: confloat(ge=0.0)
    memMb: confloat(ge=0.0)
    tempC: float
    throttled: bool
    diskFreePct: confloat(ge=0.0, le=100.0)


class Severity(StrEnum):
    critical = 'critical'
    notable = 'notable'


class AdsbInteresting(BaseModel):
    """
    topic: adsb/interesting (QoS1)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ts: int
    icao: constr(pattern=r'^[0-9a-f]{6}$')
    severity: Severity
    rule: str
    callsign: str | None = None


class MqttPayloads(
    RootModel[
        Radio2Mode
        | Radio2PassNext
        | Radio2Health
        | Radio2Command
        | AtcActivity
        | AisVessel
        | SatellitePassEvent
        | SysHealth
        | AdsbInteresting
    ]
):
    root: (
        Radio2Mode
        | Radio2PassNext
        | Radio2Health
        | Radio2Command
        | AtcActivity
        | AisVessel
        | SatellitePassEvent
        | SysHealth
        | AdsbInteresting
    ) = Field(
        ...,
        description='MQTT topic payloads. Topic tree: 03_ARCHITECTURE §5. All payloads carry ts (unix s); consumers are idempotent (QoS 1 = at-least-once).',
        title='MqttPayloads',
    )
