"""rtl_airband config generation for the ATC mode (P8.4, ADR-007).

Renders an RTLSDR-Airband config (libconfig format) that tunes SDR #2 to the
configured airband channels and streams AM audio to Icecast. The browser plays
the Icecast MP3 mount directly — no transcoding hop.

Single-tuner constraint: all monitored channels must fall within the sample
rate window (~2.5 MHz). render_config centres the tuner on the channel span and
rejects spans that don't fit, with an actionable message — better a clear
config error than silent dead channels.
"""

from __future__ import annotations

SAMPLE_RATE_HZ = 2_560_000
# usable span after DC-spike + filter-rolloff headroom (~90% of sample rate)
USABLE_HZ = int(SAMPLE_RATE_HZ * 0.9)


class AirbandConfigError(ValueError):
    """Channels don't fit one tuner window — message tells the user what to do."""


def _mount(freq_mhz: float) -> str:
    return f"atc_{int(round(freq_mhz * 1000))}"  # 118.1 → atc_118100


def _device_block(serial: str, gain: float, center_mhz: float, remote_url: str | None) -> str:
    """rtlsdr-local, or soapysdr-remote when capturing on the other node (ADR-009).
    NOTE: rtl_airband SoapySDR field syntax is validated at hardware bring-up (R1)."""
    common = (
        f"  gain = {gain};\n"
        f"  centerfreq = {center_mhz:.4f};\n"
        f"  sample_rate = {SAMPLE_RATE_HZ // 1000};"
    )
    if remote_url:
        dev = f"driver=remote,remote={remote_url},driver=rtlsdr,serial={serial}"
        return f'  type = "soapysdr";\n  device_string = "{dev}";\n{common}'
    return f'  type = "rtlsdr";\n  serial = "{serial}";\n{common}'


def render_config(
    channels_mhz: list[float],
    *,
    serial: str,
    icecast_host: str,
    icecast_port: int = 8000,
    icecast_password: str = "hackme",
    gain: float = 28.0,
    primary_mount: str = "atc",
    remote_url: str | None = None,
) -> str:
    """Build the rtl_airband.conf text. First channel also streams to
    `primary_mount` (the URL the dashboard plays). When `remote_url` is set
    (e.g. tcp://10.55.0.1:55132), the SDR is read over SoapyRemote (ADR-009)."""
    if not channels_mhz:
        raise AirbandConfigError("no ATC channels configured (radio2.atc.channels_mhz)")
    for ch in channels_mhz:
        if not (118.0 <= ch <= 137.0):
            raise AirbandConfigError(f"channel {ch} MHz outside airband 118–137 MHz")

    lo, hi = min(channels_mhz), max(channels_mhz)
    span_hz = (hi - lo) * 1e6
    if span_hz > USABLE_HZ:
        usable = USABLE_HZ / 1e6
        raise AirbandConfigError(
            f"channels span {span_hz / 1e6:.1f} MHz but one tuner covers ~{usable:.1f} MHz; "
            f"pick channels within ~{usable:.1f} MHz of each other"
        )
    center_mhz = round((lo + hi) / 2, 4)

    chan_blocks = []
    for i, ch in enumerate(channels_mhz):
        outputs = [_icecast_output(icecast_host, icecast_port, icecast_password, _mount(ch))]
        if i == 0:
            outputs.append(
                _icecast_output(icecast_host, icecast_port, icecast_password, primary_mount)
            )
        chan_blocks.append(
            f"""    {{
      freq = {ch:.4f};
      modulation = "am";
      outputs: (
{",".join(outputs)}
      );
    }}"""
        )

    device = _device_block(serial, gain, center_mhz, remote_url)
    return f"""# generated by sdr-telemetry-node radio2 — do not edit by hand
devices: ({{
{device}
  channels: (
{",".join(chan_blocks)}
  );
}});
"""


def _icecast_output(host: str, port: int, password: str, mount: str) -> str:
    return f"""        {{
          type = "icecast";
          server = "{host}";
          port = {port};
          mountpoint = "{mount}";
          username = "source";
          password = "{password}";
          name = "{mount}";
          genre = "ATC";
        }}"""
